TRAIN_FROM_SCRATCH: True

DATALOADER:
  NUM_WORKERS: 4
  TRAIN_X:
    BATCH_SIZE: 128
  TRAIN_U:
    SAME_AS_X: True
  TEST:
    BATCH_SIZE: 256

OPTIM:
  NAME: 'sgd'
  LR: 0.01
  MAX_EPOCH: 20
  STAGED_LR: False

MODEL:
  BACKBONE:
    NAME: 'dtn'
  HEAD:
    NAME: 'mlp'
    HIDDEN_LAYERS: [256]
    DROPOUT: 0.5
  CLASSIFIER:
    TYPE: 'weight'