TRAIN_FROM_SCRATCH: True

INPUT:
  SIZE: (28, 28)
  PIXEL_MEAN: (0.5,)
  PIXEL_STD: (0.5,)
  MODE: 'L'

DATALOADER:
  NUM_WORKERS: 4
  TRAIN_X:
    BATCH_SIZE: 128
  TRAIN_U:
    SAME_AS_X: True
  TEST:
    BATCH_SIZE: 256

OPTIM:
  NAME: 'sgd'
  LR: 0.01
  MAX_EPOCH: 20
  STAGED_LR: False

MODEL:
  INIT_WEIGHTS: 'output/shot_source/digit/mnist2usps/model/model.pth.tar-20'
  BACKBONE:
    NAME: 'lenet'
  HEAD:
    NAME: 'mlp'
    HIDDEN_LAYERS: [256]
    DROPOUT: 0.5
  CLASSIFIER:
    TYPE: 'weight'
