TRAIN_FROM_SCRATCH: True

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 64

OPTIM:
  NAME: 'sgd'
  LR: 0.01
  STEPSIZE: [100]
  MAX_EPOCH: 30
  STAGED_LR: True
  NEW_LAYERS: ('head', 'classifier')

MODEL:
  BACKBONE:
    NAME: 'resnet101'
  HEAD:
    NAME: 'mlp'
    HIDDEN_LAYERS: [256]
    DROPOUT: 0.5

TRAIN:
  PRINT_FREQ: 2

TEST:
  SPLIT: 'test'
  NO_TEST: True